name: tangram-env
dependencies:
  - python>=3.9.0
  - pip=20.2.2
  - scipy=1.5.2
  - matplotlib-base=3.3.1
  - seaborn=0.11.1
  - jupyterlab=2.2.6
  - nb_conda=2.2.1
  - pip:
    - torch==1.4.0
    - numpy>=1.22
    - pandas==1.2.0
    - scanpy>=1.6.0
    - scikit-learn
    - tqdm
